---
title: "Introduction"
author: "Cy Coldiron"
format: pdf
editor: visual
---

“It has become standard fare in American politics to watch each party rail against deficits when they are out of power but hungrily embrace deficits when in control and able to advance their own agenda.” — **Kenneth Rogoff**, *Our Dollar, Your Problem*

## 1.1 Background

Debates over the size and scope of the Federal Deficit have been a central feature of American politics since its inception. Beginning as a constitutional question in the 1790s, deficits became increasingly normalized in the 20th century with the rise of Keynesian economics—and were seen as both a war-time necessity and a tool for effective stabilization policy. By the late twentieth century, deficit discourse turned uniquely partisan. Political leaders, including President Ronald Reagan, attributed economic woes—including record high inflation—to the opposition parties' excessive spending policies. Reagan's rhetorical campaigns illustrated the role of effective communication in generating political success and influencing public perceptions, influencing the coming decades of combative politics. In the modern era of U.S politics, characterized by large government spending and polarization, each party has used social media to represent the opposing party as the issue to America’s persistent deficits. 

Aside from the Federal Deficits centrality in American political discourse, the national debt itself has far-reaching implications for both the domestic and global economy. Beyond the stimulus effects of deficit spending, long-term imbalances can exacerbate inflationary pressures, burden future generations with higher borrowing costs, and contribute to asset bubbles and macroeconomic instability. Yet despite both the rhetorical and economic significance of deficits —there exists little empirical analysis of when and why deficit rhetoric is used by elected officials. For instance, does political attention to the national deficit increase in response to rising debt levels—and is it correlated with other macroeconomic outcomes? And, does an elected official's deficit rhetoric change in response to their power status or during legislative periods? This paper seeks to answer these questions. By analyzing 3.6M tweets from U.S congressional members from 2017-2023, we examine the evolution of deficit rhetoric and analyze how messaging varies across institutional contexts, legislative periods, and macroeconomic conditions, providing the first large-scale empirical assessment of how deficit rhetoric functions within the incentive structure of American politics.

Instead of treating deficit rhetoric as a direct proxy for fiscal concern, this study investigates its use in response to changes in underlying political and economic circumstances. If deficit rhetoric is driven by fiscal fundamentals, then references to the national debt should be correlated with the growth of the deficit itself. Alternatively, if deficit rhetoric is a function of political incentives, then it should vary systematically with shifts in institutional power or during legislative periods. Distinguishing between these two outcomes is central to this paper and in understanding the contemporary state of American fiscal discourse.

## 1.2 Motivation

Political discourse can influence public perceptions on the national debt. If this is the case, then changes to public opinion on deficit spending may influence legislative agendas—giving more or less political capital for party leaders to advance policy agendas. For instance, if online deficit rhetoric impacts public support for fiscal stimulus—then the majority party's legislative agenda may be forced to change, thereby impacting the economic trajectory of the country. In addition to economic influence, deficit rhetoric can have substantial impacts on political outcomes. Considering deficit rhetoric shapes voters' beliefs about the fiscal responsibility of elected officials and the parties they represent—political entities that are more persuasive in their online messaging, whether that be denigrating the opposition, or advocating for their own policies, will have greater success in electoral campaigns and in influencing public opinion. Elected officials then have a prerogative to communicate about the deficit in such a way that maximizes their political outcomes. By analyzing the rhetorical patterns of these officials—we can understand how political actors use the Federal Deficit, across varying institutional and economic contexts, to influence voters beliefs, and shape public opinion. 

## 1.3 Why Twitter (X)?

Twitter (now X) is a uniquely effective medium for this analysis. It is widely and consistently used by members of Congress, and is a direct representation of each representative’s rhetorical intentions. Tweets are standardized in format—meaning each post is timestamped, have the same character constraints, and are tied to verifiable individuals, thereby allowing for large-scale and reproducible time-series analysis. Tweets, unlike floor speeches or hearings—which vary in length and frequency—are published daily by almost all congressional members. This provides a far more comprehensive dataset (in this case 3.6M tweets), giving us greater statistical power, and allowing us to draw stronger conclusions about key explanatory relationships. 

\
