---
title: "Literature Review"
author: "Cy Coldiron"
format: pdf
editor: visual
---

## 2.1 Overview of Deficit Rhetoric Literature

A substantial body of literature has examined partisan differences in U.S. federal deficit spending. While this research provides extensive analysis of actual fiscal outcomes—i.e, debt accumulation across presidential administrations and macroeconomic conditions—it offers no insight into the political communication surrounding the national debt itself. In fact, much of the research relies on assumptions about the fiscal preferences and communication styles of parties — for instance, that Republicans are more 'deficit hawkish' or that opposition parties mention the deficit more often. Aside from our research, there is minimal systematic data on how deficit rhetoric varies across political contexts.

Given the wide scope of our analysis, it is beneficial to examine three key research areas to contextualize this research and its practical significance better. First, we will examine the underlying political incentives driving variation in deficit tweeting—i.e., why do tweeting rates change across political contexts? Second, given that the medium of analysis is Twitter, we will examine the role of social media in modern political communication—i.e., how politicians use it and how it impacts broader political outcomes. Lastly, we will explore the growing body of research relating to text labeling and various approaches to empirically measuring online rhetoric.

## 2.2 The Political Incentives of Deficit Rhetoric 

Kent Weaver's theory of blame avoidance offers a plausible theory for why variation should occur. Given that voters are more sensitive to negative outcomes than positive ones (negativity bias), politicians are motivated to be 'blame minimizers',  not 'credit maximizers'. Simply put, politicians achieve better political outcomes by suppressing negativity than by advocating their achievements. Weaver notes that blame avoidance is most pronounced for policies with the highest visible costs (e.g, budget cuts, tax increases), which also have the greatest political impact, given voters' negativity bias. Under Weaver's framework, governing parties would therefore have an incentive to suppress deficit rhetoric to minimize the visibility of a loss-allocating topic (the national debt). Weaver's research also highlights a key distinction between governing powers: while majority parties can legislate and initiate policy, the opposition party has one key source of power—blame generation. These contrasting incentive structures would explain why minority parties tweet at higher rates: because the national debt is a negative-sum game, opposition parties have an incentive to increase deficit rhetoric, thereby generating blame for the governing party and likely improving their own political popularity. 

Justin Grimmer offers a complementary theory of what drives political communication, asserting that communication is used to signal ideology that benefits politicians' electoral positioning. This framework could explain why members emphasize the deficit more: politicians want to signal to voters that they are fiscally responsible. If, for example, Republican voters value fiscal responsibility, Republican politicians would be motivated to emphasize the deficit to signal their hawkish ideology. This assumption about Republican voters' preferences would help explain why Republicans, generally speaking, have higher deficit-tweeting rates. Grimmer also makes an important distinction between public communication and voting patterns: what legislators say publicly is not the same as how they vote. Representatives may tweet about the deficit for electoral and ideological reasons, but also vote in favor of deficit spending due to political constraints (party leadership, coalition requirements, etc.). Such a phenomenon would explain how some congressional members have historically supported fiscal stimulus while also having relatively high deficit tweeting rates.

## 2.3 Social Media as Strategic Political Communication

A growing body of research has studied the dynamics of political communication on social media. Jacob Straus (2018) tracks congressional adoption rates of social media, showing that usage is now a normalized and necessary aspect of political communication. Research also shows an increasing influence of social media communication on political outcomes, including legislation, public opinion, and even news cycles. For instance, Shapiro & Hemphill (2016) show that congressional tweets can predict next-day coverage in the New York Times. Their research shows that journalists rely on these political tweets, which they call an ‘information subsidy’, as a primary source of material for news coverage. Fabrizio Gilardi (2021) extends this finding by showing that politicians' tweets on specific topics increase subsequent coverage of those issues across all media platforms (not just the NYT). 

Under these frameworks, deficit tweeting could be seen as a mechanism to drive favorable political news cycles. If a politician or political party wants media outlets to cover the federal deficit, they would be incentivized to tweet more frequently, thereby "subsidizing" the topic's chances of coverage. This could help explain the variation in tweeting rates among Republicans. For instance, during the passage of Democratic legislation (e.g., the IRA), Republicans would have reason to tweet more often about the national debt to increase the likelihood of negative news coverage and reduce the bill's popularity. Taken together, their research shows that tweets are neither random nor insignificant—but instead a calculated communication tool shaping media narratives and political outcomes.

## 2.4 Measuring Political Rhetoric

With the growing influence of social media in shaping political outcomes, there have been significant advances in empirical methods for text analysis. Grimmer & Stewart (2013) claim text analysis is fundamentally a measurement problem. And, the corresponding empirical method one should use—whether it be a dictionary, supervised, or unsupervised approach—should be a function of the variable you are seeking to measure. For instance, dictionary-based approaches are well-suited for measuring topics that are explicitly referenced. Because deficit rhetoric is primarily referenced through direct phrases—such as ‘federal deficit, or ‘national debt’—this approach makes the most logical sense. Additionally, this approach allows for greater transparency, reproducibility, and iteration: one can easily adjust the size and focus of the dictionary to better capture references to the national debt. While providing greater flexibility, dictionary-based methods, especially compared to a supervised learning approach, are less adept at capturing implicit references—a topic we will further explore in the section XYZ.
