---
title: "Discussion Section"
author: "Cy Coldiron"
format: pdf
editor: visual
---

## 

## 6.1 Core Empirical Findings

Our research finds that deficit rhetoric on Twitter among U.S. congressional members is low—fluctuating between averages of .5% to 2% throughout the six-year periods (or 5-20 “deficit tweets” per 1000 tweets). However, our results highlight significant and important nuances. Specifically, we find that variation in deficit tweeting is strongly tied to two factors: relative institutional power and legislative timing. We also find that deficit rhetoric is not tied to the fiscal magnitude of policy bills—that is, tweeting rates are uncorrelated with the long-term fiscal impact of legislation (measured by its 10-year CBO estimate).

## 6.2 Institutional Power and Strategic Communication

Institutional power—whether a member's party holds congressional and or executive control—is a key determinant of deficit tweeting among Republicans, but not Democrats, and it helps to explain significant variations in tweeting gaps among the parties. Republicans deficit rhetoric increases five-fold (.2% to 1%) when transitioning into out of power-contexts (holding all other factors constant) while Democrats rates remain constant throughout. Republican leaders mirror the trends of their rank-and-file members (increase deficit in out-of-power contexts), while Democratic leaders show no discernible pattern in contextual tweeting among each other. 

Regression analysis also indicates that legislative windows influence deficit tweeting only after conditioning on presidential and or congressional control. In other words, Republican-Democrat tweeting differences only change once we consider who is in power: the partisan tweeting gap contracts in legislative months where Democrats hold the presidency. 

These results suggest that, for Republicans, deficit rhetoric functions as a context-dependent communication resource: members will emphasize the deficit when political accountability is externalized—that is, when Democrats hold power. Republicans, especially among their leadership, will lessen such deficit tweeting when legislative responsibility is internalized. 

## 6.3 Fiscal Conditions, Policy Substance, and the Limits of Economic Explanations

Results show no discernible relationship between the fiscal magnitude of legislation and deficit tweeting: members do not increase references to the deficit in legislative periods that are characterized by large spending. In other words, deficit tweeting is the same for policy bills that have a low fiscal impact (such as the Inflation Reduction Act) and legislation with high fiscal impact (such as the Tax Cuts and Jobs Act). And, the fiscal magnitude of bills does predict tweeting gaps once institutional controls are included. 

Common sense would suggest that deficit rhetoric should derive from the very thing it is in reference to: the Federal Deficit. Our research, however, suggests that no such relationship exists. Instead, communication patterns appear a function of political contexts—not fiscal circumstances. This is an important relationship, or lack thereof, that stakeholders (voters, journalists, and forecasters) should understand: deficit rhetoric, most of the time, should not be interpreted as a direct proxy for fiscal concern, but rather as a reflection of a representative's power and political incentives.

## 6.4 Party Asymmetry and Organizational Messaging Patterns

Our research shows two important asymmetries between political parties' communication patterns. First, Republicans exhibit greater sensitivity to power status: their deficit tweeting averages fluctuate greatly depending on who controls Congress and the presidency. 

The second asymmetry which warrants consideration, is the difference in coordination and alignment among party leaders and rank-and-file members. While preceding analysis covers broader party-level trends, exploring individual leaders’ tweeting patterns provides us insight into how key political figures communicate about the deficit in varying institutional contexts. Examining these trends can help illustrate the degree of strategic communication employed by top legislators, and by extension—the party they represent. 

For instance, consider Representative Paul Ryan—a self-described fiscal conservative, Speaker of the House from 2017-2019, and a central political figure in modern discourse surrounding the national deficit. While Ryan frequently branded himself a “deficit hawk,” his public deficit messaging was minimal during unified GOP control as Congress advanced the Tax Cuts and Jobs Act, which the CBO estimated would add roughly \$1.5 trillion to the debt over ten years. In short, Ryan rarely emphasized the deficit while orchestrating a major deficit-increasing legislative agenda. Ryan’s seemingly paradoxical messaging behavior is emblematic of the claim we have highlighted in this section: deficit messaging, especially for Republicans, is not a proxy for genuine fiscal worries, but is a reflection of a representative's political incentives. 

While previous research establishes the growing polarization in congressional ideology and party-line voting (CQ Roll Call 2024), my findings provide insight into the specific polarities of a single rhetorical subject—the federal deficit. This research allows us to see the extent to which party leaders—and by extension, the parties they represent—cyclically align their rhetoric to serve political means.

Mitch McConnell serves as an effective illustration: he is the only Republican to serve as both the minority and majority leader during this timeframe. As Figure 6 shows, during his four-year role as majority leader he tweeted about the deficit just three times in 5622 total tweets—a staggering 0.05% deficit-tweet rate. This serves in sharp contrast to his tweeting patterns as the minority leader, under President Joe Biden, where McConnell’s deficit tweeting rates increased to 1.89%—a 38-fold increase. Speaker McConnell—who is, both formally and informally, the spokesperson for the Republican party—made a conscious effort to vastly alter his deficit-rhetoric during his time in the opposition. And, the broader Republican party followed in lock-step with his messaging goal. These patterns suggest a top down messaging dynamic among Republicans: party leaders establish rhetorical cues that are consequently adopted by rank-and-file members.

These patterns are in contrast to the Democratic party which illustrate both less intra-party coordination and less sensitivity to changes in their relative power. For instance, the divergent tweeting patterns of Speaker Pelosi and Senator Schumer suggest a comparatively weaker intra-party alignment in messaging. Ms. Pelosi tweets at higher rates in the minority versus majority (1.11 vs 0.50), while Mr. Schumer tweets at significantly higher rates in the majority (1.03 vs 4.00).  Our results suggest that Democratic messaging is far more heterogeneous at both the leadership level (Pelosi and Schumer), and among rank-and-file members themselves. Overall, we see that Republicans—intentional or not—are far more successful in articulating organized and context-specific messaging.

## 6.5 Broader Implications for Political Communication

Effective communication is a key determinant in political success. And as the avenues for maximizing political outreach have become progressively centered around social media, it is becoming increasingly important to analyze, and understand the messaging strategies deployed by political representatives, and the parties they represent. In understanding the relative frequency in which politicians emphasize a specific topic, such as the Federal Deficit, we can begin to understand both the messaging goal of that specific entity, and the political incentives that are catalyzing such communication.

## 6.6.1 Incentives and Congressional Communication

While the precise motivations underlying elected officials’ communication choices cannot be directly observed—i.e, we cannot know the reasoning behind every tweet—the systematic patterns in our data provide a constructive foundation for interpretive analysis. First, there is little evidence that deficit tweeting is exclusively, or even partly, a function of the actual deficit itself: there is minimal correlation between the growth of the deficit and tweeting rates. The most plausible explanatory factor driving deficit rhetoric is then the political incentive to externalize fiscal blame on the opposing party. The reasoning is the following: minority parties, while lacking any real legislative, governing, or subpoena power, have the capacity to frame the opposing party as fiscally irresponsible in hopes of improving their popularity or electoral prospects. In fact, messaging campaigns become the primary tool that minority parties use to improve their relative positioning. This political incentive, however, disappears once a party gains legislative control. Thus, it no longer becomes politically advantageous to discuss—or in this case, tweet—about the Federal Deficit. 

Consider this framework applied to the Republican party. From 2017-2021 the GOP had mostly majority legislative control (aside from losing the house in 2019). Considering they are the ones with “the power of the purse”, there exists no political prerogative to mention the Federal Deficit. Rather, they want to focus their messaging on convincing the public that their current governance and policies are improving the country—not on why such policies may be contributing to the growth of the national debt. However, once they no longer have legislative power (2021-2023), their political incentives reverse, motivating them to now externalize fiscal blame to the Democratic party. Through this lens, we can view deficit rhetoric not as proxy for fiscal concern, but as a political tool that is used when political parties no longer have power through traditional congressional means. 

## 6.6.2 Deficit Rhetoric in an Era of Elevated Debt & Social Media

Deficit rhetoric, particularly on social media, will likely remain a central feature of political discourse—both in electoral campaigns and day-to-day messaging. First, the underlying fiscal conditions of the U.S, characterized by record high debt levels, elevated borrowing costs, and financial de-globalization, suggest that the federal deficit will play an even more important role in determining the spending patterns and economic trajectory of the country. Additionally, the growing centrality of social media as a channel for communication makes understanding such trends even more important.

## 6.6.3 Implications for Voters, Journalists, and Public-Facing Institutions

Voters make decisions based on their interpretation of candidates policy and governing intentions. These interpretations are partly constructed through the information voters consume—whether that be through speeches, interviews, or social media posts. Thus, if voting decisions are based on a specific topic, such as the national debt, then voters will naturally prefer candidates who choose to align with such preferences. However, in the case of the federal deficit, political messaging around the national debt (for the most part) is not a reflection of genuine fiscal concern, but is instead a reflection of institutional positioning and political incentives. Therefore, it is essential for those who consider the national debt as a significant factor in voting decisions to understand the underlying political incentives driving a politician's messaging. Our research suggests that an uptick in a representative's deficit rhetoric will more often than not reflect a change in political contexts (power status, legislative timing) rather than a sincere change in policy perspective. Voters should therefore be cognizant of the current political atmosphere when drawing conclusions of a representative or candidates opinions on the national debt.

As stated previously, voters (and the public more broadly) form their political decisions and opinions based on the information and news they consume. As a consequence, the media plays an outsized role in forming current and future political environments. Thus, it is imperative for journalists to understand the relationship surrounding deficit rhetoric and political incentives so as to maximize the objectivity, and fairness, of their political coverage. For instance, it would be incomplete journalism to represent Senator Mitch McConnell’s relatively frequent deficit messaging from 2021-2023 without contextualizing his staggering low rates from 2017-2021 (0.05%). This research provides a solid foundation for journalistic coverage of the Federal Deficit. When covering a political party or representative’s opinions regarding the national debt, media coverage should be aware of previous trends and current political contexts so as to appropriately contextualize the situation. 

Understanding the dynamics of deficit rhetoric is important for any stakeholders (researchers, forecasters, political strategists) whose decisions are based upon the messaging of representatives and political parties more broadly. Thus, similar to voters and journalists, impacted entities should understand the dynamic between political contexts and political messaging when constructing forecasts and making decisions.

## 6.7 Directions for Future Research

Our research, while comprehensive in many respects, is solely focused on deficit tweeting rates among U.S. congressional members from 2017-2023. This leaves many avenues for supplemental research. Most notably, future research could examine whether the trends identified here extend beyond Twitter— whether that be to other social media platforms or to other communication channels entirely, including floor speeches, press releases, fundraising emails, or televised appearances. Moreover, it would be informative to perform similar analysis from either a more recent or larger timeframe—giving us greater insight into how parties, political leaders, and rank-and-file members change their messaging across fiscal and political contexts including the 2024 election and the passage of the Big Beautiful Bill (2025).

A second consideration would be to analyze the degree of engagement (likes, retweets, views etc). One could examine whether engagement interacts with political contexts (power status, legislative periods etc). Such analysis would help to inform us on the degree to which political incentives shape deficit rhetoric. For instance, there may be an additional political incentive for representatives to engage in such tweeting when it benefits their engagement levels systematically.

\
\

\
