---
title: "Fiscal Policy vs. Political Communication"
author: "Cy Coldiron"
format: pdf
editor: visual
---

\setcounter{section}{1}

# Fiscal Policy vs. Political Communication

## Existing Research on Fiscal Outcomes and the Absence of Deficit Rhetoric Analysis

A substantial body of literature has examined various aspects of U.S. federal deficit spending and the partisan nature of public finance more broadly (Alesina & Tabellini 1990; Pettersson-Lidbom 2001; Alesina & Passalacqua 2016). This research provides extensive insight into the determinants of fiscal outcomes, including how political institutions, electoral incentives, and partisan control over legislation influence government spending decisions.

While this research provides extensive analysis of actual fiscal outcomes, it offers little insight into the actual political communication surrounding the national debt itself. To our knowledge, this paper is the first comprehensive analysis of how politicians’ deficit-related messaging varies with political contexts and fiscal circumstances.
